### ISSUE TITLE
Audio control

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/dwm#10]
I use mod+backslash to toggle my volume ( vol-toggle.sh ), but my dwm status bar can't feedback the volumn switch.

**Comment by KiteAB** [comment]
For example, my volume is 45%, and then I press mod+backslash, the status bar still shows 45%, but I can’t hear it when playing audio and video, I try to manually refresh the status bar, the problem remains

**Comment by theniceboy** [comment]
Not an issue of this repo

**Comment by KiteAB** [comment]
Oh, yes. dwm-status-refresh.**sh**

**Comment by KiteAB** [comment]
[#2](https://github.com/theniceboy/scripts/issues/2)
