### ISSUE TITLE
dwm状态栏&unicode问题

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/dwm#11]
dwm状态栏的内存图标是在左上角的
所有状态栏的unicode图标（除了tag上的图标）都被向左上角压缩了
我看你之前视频里也有这个问题 讲lg的视频里又正常了 /笑哭
我的电池显示部分如果是插电就显示个插座头 你那直接是个头子加s形的线了 wwww

![2020-07-19_20-16.png](https://i.loli.net/2020/07/19/sR1njamZ97GQJo4.png)

**Comment by KiteAB** [comment]
不知道该归类到字体问题还是dwm问题   或者dpi问题  /笑哭

**Comment by Ahacad** [comment]
同样是状态栏里的东西会往上移动一些，不过没什么大的影响。
电池图标的问题应该可以直接去找想要的图标对应的unicode，然后在xsetroot里更改？

想另外请问一下你所有tag的图标（方便再截个图？）和对应的unicode，看起来tag上的并不是汉字？

**Comment by KiteAB** [comment]
我的仓库中也有个dwm   你可以从那里面的config.h看到unicode码

**Comment by KiteAB** [comment]
"respawn" this issue then make it on my github main page again

**Comment by theniceboy** [comment]
这个问题解决了吗？

**Comment by KiteAB** [comment]
还没 一直沉在这/笑哭

**Comment by theniceboy** [comment]
这个就跟你的字体有关系，我从你给的图中也看不到什么问题。

**Comment by KiteAB** [comment]
我的字体也是SauceCodePro Nerd Font Mono啊  就是内存显示左边的那个类似光盘的unicode图标并没有平行于状态栏 没有向下图一样放到最大
![img](https://kyun.ltyuanfang.cn/tc/2020/08/10/414aee7ffbb45.png)

**Comment by KiteAB** [comment]
![](https://kyun.ltyuanfang.cn/tc/2020/08/10/414aee7ffbb45.png)

**Comment by KiteAB** [comment]
我发的图自己看不到。。。
https://kyun.ltyuanfang.cn/tc/2020/08/10/414aee7ffbb45.png

**Comment by theniceboy** [comment]
你得装emoji字体。

**Comment by KiteAB** [comment]
[.config](https://github.com/theniceboy/.config)里提到的字体我除了`twemoji-color-font`都装了  可能就是这个的问题吧/笑哭
