### ISSUE TITLE
想问下哪里是设置默认布局

### ISSUE THREAD

**Issue by zenyarn** [theniceboy/dwm#14]
我从aur里下的dwm默认是左右布局的，就是主窗口在左，别的窗口在右
然后编译安装了以后变成了主窗口在上，剩下的在下面，横着一长串很不方便，自己找从哪里设置也没找到
没在 config.h 里找到相关变量

**Comment by theniceboy** [comment]
[https://wiki.archlinux.org/index.php/Dwm](https://wiki.archlinux.org/index.php/Dwm)
