### ISSUE TITLE
当窗口没有软件时modkey+e会注销！

### ISSUE THREAD

**Issue by kangxiaoju** [theniceboy/dwm#16]
比如，一桌面没有软件，我这个时候使用快捷键modkey+e或者modkey+u切换软件的时候会把系统注销了，很多时候会误操作导致注销。
我不清楚是bug还是设计就是这样的或者是就我这边会这样？
系统：arch

**Comment by kangxiaoju** [comment]
对了，使用的是lightdm

**Comment by theniceboy** [comment]
我刚才空桌面试了一下没有注销，你能具体说一下你的情况吗？还有linux内核版本

**Comment by kangxiaoju** [comment]
> 我刚才空桌面试了一下没有注销，你能具体说一下你的情况吗？还有linux内核版本

内核版本：5.11.2-arch1-1

主要出现的问题就是我在没有打开任何软件的情况下，不小心摁了modkey+e切换程序的快捷键后，系统就注销了

如果你没有出现的话有可能是我这边修改你的配置出现问题，我在重新搞几次找一下问题

**Comment by loverainye** [comment]
同样问题，启动方式 startx ，系统arch 内核 5.11.6-zen1-1-zen ，5.11，内存16G，intel集成显卡 。
还有单个桌面打开50+终端窗口也会崩溃 ，在所有桌面累积窗口多的情况modey+0也会崩溃。

**Comment by ysl2** [comment]
同样问题，内核5.12.9-1，系统manjaro，通过sddm启动。并且我没有改动@theniceboy的任何配置，但仍出现此bug

**Comment by ysl2** [comment]
老哥们如果解决了，请告诉我一声 :-) 多谢各位@theniceboy @loverainye @kangxiaoju

**Comment by ysl2** [comment]
是awesomebar导致的，在官网上有新的patch发布了，修复了这个问题
