### ISSUE TITLE
How to start use dwm?

### ISSUE THREAD

**Issue by wind13** [theniceboy/dwm#2]
I am using Manjaro KDE, how can I switch to dwm? and can I easy to switch back to Manjaro KDE?

**Comment by theniceboy** [comment]
我把你的问题放到搜索引擎进行了搜索操作：[搜索结果](https://www.google.com/search?sxsrf=ACYBGNTQoz859WdwUJojHm3hxKuV9f6yIA%3A1577196238995&ei=zhoCXuKuPNP4-wSHoaioDQ&q=I+am+using+Manjaro+KDE%2C+how+can+I+switch+to+dwm%3F+and+can+I+easy+to+switch+back+to+Manjaro+KDE%3F&oq=I+am+using+Manjaro+KDE%2C+how+can+I+switch+to+dwm%3F+and+can+I+easy+to+switch+back+to+Manjaro+KDE%3F&gs_l=mobile-gws-wiz-serp.3...2928.2928..3768...2.0..0.232.232.2-1......0....1j2.......8..35i362i39.8WUqlPubjNk)

接下来，我点击了搜索结果中的第一条：[网址](https://forum.manjaro.org/t/dwm-not-showing-in-lightdm-log-in-screen/98220)

这样，我就得到了答案

**Comment by wind13** [comment]
哈哈……没出墙，用的是 bing.com，所以得到了这个：[搜索结果](https://cn.bing.com/search?sxsrf=ACYBGNTQoz859WdwUJojHm3hxKuV9f6yIA%3A1577196238995&ei=zhoCXuKuPNP4-wSHoaioDQ&q=I+am+using+Manjaro+KDE%2C+how+can+I+switch+to+dwm%3F+and+can+I+easy+to+switch+back+to+Manjaro+KDE%3F&oq=I+am+using+Manjaro+KDE%2C+how+can+I+switch+to+dwm%3F+and+can+I+easy+to+switch+back+to+Manjaro+KDE%3F&gs_l=mobile-gws-wiz-serp.3...2928.2928..3768...2.0..0.232.232.2-1......0....1j2.......8..35i362i39.8WUqlPubjNk)
看来还是 google 强大。

**Comment by KiteAB** [comment]
其实还有个办法启动   自己写个session文件
