### ISSUE TITLE
特来感谢你

### ISSUE THREAD

**Issue by Wjinlei** [theniceboy/dwm#3]
兄弟，从B站发现你后，发现你真的很厉害，看起来和我差不多大，但比我厉害太多。这段时间从你身上吸收学习了很多，现在我的linux也打造的我自己看起来非常爽了，和你学习了vim、i3、dwm、st、ranger、compton、nvim。真是太爽了，现在我的工作效率提升了一大截，以前都用桌面环境，现在只用dwm，反正一个字，爽！你是我学习的目标。我现在也用github了。以前github也用的少。以后多多向你学习，特来感谢！！！ 牛

**Comment by theniceboy** [comment]
很高兴我的视频能帮到你！你发现的好东西也欢迎和我分享啊～ 可以发我邮件b站私信什么的 互相学习
