### ISSUE TITLE
sudo make clean install 编译会报错好像是因为  dwm-vanitygaps-20190508-6.2.diff 

### ISSUE THREAD

**Issue by ghost** [theniceboy/dwm#4]
sudo make clean install 能编译成功，但是编译过程中有报错信息，好像是因为  dwm-vanitygaps-20190508-6.2.diff
我的GCC版本是gcc9.2.0

drw.c: In function ‘drw_text’:
drw.c:330:7: warning: ‘ew’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  330 |     w -= ew;
      |     ~~^~~~~
dwm.c: In function ‘drawbar’:
dwm.c:886:6: warning: unused variable ‘boxw’ [-Wunused-variable]
  886 |  int boxw = drw->fonts->h / 6 + 2;
      |      ^~~~
dwm.c:885:6: warning: unused variable ‘boxs’ [-Wunused-variable]
  885 |  int boxs = drw->fonts->h / 9;
      |      ^~~~
dwm.c: In function ‘runAutostart’:
dwm.c:1764:2: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
 1764 |  system("cd ~/scripts; ./autostart.sh &");
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At top level:
dwm.c:2024:1: warning: ‘incrivgaps’ defined but not used [-Wunused-function]
 2024 | incrivgaps(const Arg *arg)
      | ^~~~~~~~~~
dwm.c:2013:1: warning: ‘incrihgaps’ defined but not used [-Wunused-function]
 2013 | incrihgaps(const Arg *arg)
      | ^~~~~~~~~~
dwm.c:2002:1: warning: ‘incrovgaps’ defined but not used [-Wunused-function]
 2002 | incrovgaps(const Arg *arg)
      | ^~~~~~~~~~
dwm.c:1991:1: warning: ‘incrohgaps’ defined but not used [-Wunused-function]
 1991 | incrohgaps(const Arg *arg)
      | ^~~~~~~~~~
dwm.c:1980:1: warning: ‘incrogaps’ defined but not used [-Wunused-function]
 1980 | incrogaps(const Arg *arg)
      | ^~~~~~~~~
dwm.c:1969:1: warning: ‘incrigaps’ defined but not used [-Wunused-function]
 1969 | incrigaps(const Arg *arg)
      | ^~~~~~~~~
dwm.c:1958:1: warning: ‘incrgaps’ defined but not used [-Wunused-function]
 1958 | incrgaps(const Arg *arg)
      | ^~~~~~~~
dwm.c:1952:1: warning: ‘defaultgaps’ defined but not used [-Wunused-function]
 1952 | defaultgaps(const Arg *arg)
      | ^~~~~~~~~~~
dwm.c:1945:1: warning: ‘togglegaps’ defined but not used [-Wunused-function]
 1945 | togglegaps(const Arg *arg)
      | ^~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from dwm.c:29:
In function ‘strncpy’,
    inlined from ‘arrangemon’ at dwm.c:492:2:
/usr/include/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 16 equals 
destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘setlayout’ at dwm.c:2041:2:
/usr/include/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));

**Comment by theniceboy** [comment]
可能是有一些我打了的patch你没有，所以有一堆变量没有用过的警告

**Comment by ghost** [comment]
> 可能是有一些我打了的patch你没有，所以有一堆变量没有用过的警告

我是clone后直接make clean install的
项目里的 dwm.c config.h 没有打补丁吗？
需要自己手动在打一遍？

**Comment by ghost** [comment]
算上你自己写的patches你应该打了14个patches？
patches 目录 13个文件 （少了dwm-alpha-6.1.diff）
readme 列出了 11 个 （少了 wm-scratchpad-6.2.diff dwm-focusadjacenttag-6.0.diff alphasystray.diff）

dwm-alpha-6.1.diff #readme里有，patches没有
alphasystray.diff  #官方没有，#readme没有，patches有 （我替换成官方 dwm-systray-6.2.diff）
dwm-hide-and-restore.diff #官方没有，#readme有，patches有 （#自定义补丁）

**Comment by theniceboy** [comment]
alpha可以删了，alphasystray不是官方的，dwmhideandrestore是我自己写的，readme没有更新

**Comment by ghost** [comment]
重新下载官方的6.2，，重新下载补丁，发现下面的两个补丁不能一起打，打完在编译就会报错
autostart-20161205-bb3bd6f.diff
dwm-vanitygaps-20190508-6.2.diff
