### ISSUE TITLE
dwm问题

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/dwm#5]
请问一下   怎么更新我git clone git://git.suckless.org/dwm的dwm（改过config.h,加过一堆补丁 官方网站的补丁  还有你写的hide and restore）

**Comment by KiteAB** [comment]
我已经把.git删过了。。

**Comment by theniceboy** [comment]
什么叫怎么更新？

**Comment by KiteAB** [comment]
意思就是现在dwm最新是6.2  假如出了6.3  那怎么把自己配置过的dwm更新

**Comment by theniceboy** [comment]
Diff patch

**Comment by KiteAB** [comment]
也就是看他俩的区别然后有区别的文件patch到新版dwm上？那就ez了啊

**Comment by theniceboy** [comment]
嗯，你可以用`patch`和`diff`这两个程序

**Comment by KiteAB** [comment]
> 嗯，你可以用`patch`和`diff`这两个程序

diff是要加什么参数吗  直接用diff 旧dwm 新dwm貌似不行

**Comment by theniceboy** [comment]
如果你就想直接把dwm源git repo的新commit打到你的dwm上的话，你可以这样在从git.suckless.org/dwm克隆下来的repo里来一下
```bash
git format-patch <NAME>
```
这个`<NAME>`可以是commit hash或者tag name。他会给你从这个commit hash或者tag指向对commit的下一个commit开始，每个commit生成一个patch。然后你把这些patch复制到你的dwm文件夹再`patch <`一下就ok了

我的dwm也顺便patch了一下，有一些新的commit已经没必要patch了

**Comment by theniceboy** [comment]
看了一下你的dwm，发现里面有张壁纸，没想到你也是宫崎骏粉丝哈哈  以后有问题来找我👌

**Comment by KiteAB** [comment]
> 看了一下你的dwm，发现里面有张壁纸，没想到你也是宫崎骏粉丝哈哈 以后有问题来找我

哈哈哈  彳亍口巴
