### ISSUE TITLE
一个题外问题

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/dwm#7]
我从unity官方下载了UnityHub.AppImage
我在里面点击下载了unity
然后没反应。。

**Comment by theniceboy** [comment]
1，你要注册然后有许可（免费的）
2，下下来以后你得启动。。。才能有反应

**Comment by KiteAB** [comment]
> 1，你要注册然后有许可（免费的）
> 2，下下来以后你得启动。。。才能有反应

我有许可  也登陆了
启动肯定得启动啊  ./UnityHub.AppImage

**Comment by KiteAB** [comment]
> 我从unity官方下载了UnityHub.AppImage
> 我在里面点击下载了unity
> 然后没反应。。

这个下载unity指的是点unityhub里下载unity editor

**Comment by theniceboy** [comment]
hmmm我没有遇到过这种问题，你要是录一段视频的话我也许能帮忙

**Comment by KiteAB** [comment]
我现在解决了   but这下载速度。。。
我的解决方法就是把unityhub rename成unity.exe然后放到bin里头就可以了

**Comment by theniceboy** [comment]
ok。有点意思2333

你如果还有问题的话可以把你的联系方式发到我的邮箱里，要不老在这个repo里出issue也不是个事儿哈哈

**Comment by KiteAB** [comment]
> ok。有点意思2333
> 
> 你如果还有问题的话可以把你的联系方式发到我的邮箱里，要不老在这个repo里出issue也不是个事儿哈哈

我的邮箱服务暂时有点问题  发不了邮件  可以+q吗

**Comment by theniceboy** [comment]
也ok

**Comment by KiteAB** [comment]
> 也ok

不行邮件太慢了   我q是251877082

**Comment by theniceboy** [comment]
ok加了

**Comment by KiteAB** [comment]
好的
